api_key: secret_key
api_uri: https://api.example.org
access_list:
- 192.0.2.0/24
datasets:
  mysql:
    query: 'som string'
    engine: 'mysql'
    user: 'user'
    password: 'password'
    host: 'db.example.org'
  sqlite:
    path: /srv/db/myfunkysevrvice.db
